---
- name: A Test Playbook
  hosts: all
  become: true
  vars_prompt:
    - name: ansible_password
      prompt: "Enter password"
      private: yes
    - name: ansible_become_password
      prompt: "Enter sudo password"
      private: yes
    - name: var1
      prompt: "Enter a variable"

  tasks:
    - name: First Test
      command: "uname -a"
    - debug: msg="{{ var1 }}"
