---
- name: A Test Playbook
  hosts: host1
  tasks:

    - file: 
        path: /tmp/x
        state: touch
    - file: 
        path: /tmp/z
        state: touch

    - name: Create two hard links
      ansible.builtin.file:
        src: '/tmp/{{ item.src }}'
        dest: '{{ item.dest }}'
        state: hard
      loop:
        - { src: x, dest: y }
        - { src: z, dest: k }

