---
- name: A Test Playbook
  hosts: webservers
  become: yes
  vars:
    var1: "TEST STRING 123ABC"
  tasks:

    - name: Update repo cache and install nginx package
      ansible.builtin.apt:
        name: nginx
        update_cache: yes

    - name: Make sure a service is started, enabled, and not masked
      ansible.builtin.systemd:
        state: started
        name: nginx
        enabled: true
        masked: no

    - template:
        src: templates/index.html.j2
        dest: /var/www/html/index.html
        mode: a+r

